title: Sukkari Dataset
description: A dataset for sorting Sukkari Dates
theme: just-the-docs

url: https://Dawan-AI.github.io/SukkariDataset

aux_links:
  Template Repository: https://github.com/Dawan-AI/SukkariDataset

nav_sort: case_insensitive
